import type { Metadata } from "next";

export const SITE_URL = "https://surviver.lol";

/** The link preview, generated by `app/social-card.png/route.tsx`. */
export const SOCIAL_CARD = {
  url: "/social-card.png",
  width: 1200,
  height: 630,
  alt: "Surviver.lol — 32 SaaS spots, ranked by real clicks. Every product stays live all season.",
};
export const publicPages = [
  { path: "/", title: "32 SaaS spots, ranked by real clicks", description: "Get your SaaS in front of real visitors. 32 spots at one flat fee, every product live all season, ranked by real clicks." },
  { path: "/board", title: "SaaS discovery board", description: "Explore this season's 32 SaaS products, from AI and developer tools to design and productivity. Visit the products that catch your interest." },
  { path: "/leaderboard", title: "Live SaaS leaderboard", description: "Follow the live Surviver.lol rankings: 32 SaaS products, ranked by real clicks for the whole season." },
  { path: "/seasons", title: "Tournament seasons and results", description: "Browse Surviver.lol seasons, discover past lineups, and explore permanent tournament standings and results." },
  { path: "/survivors", title: "Hall of Survivors", description: "Discover the SaaS products that outlasted their season. Explore Surviver.lol tournament winners and their earned results." },
  { path: "/enter", title: "Enter your SaaS product", description: "Submit your SaaS product to a Surviver.lol season. Choose a category, review entry details, and compete for discovery through measured visitor interest." },
  { path: "/how-it-works", title: "How it works", description: "32 spots, one flat fee. The season starts when all 32 are filled, every product stays live, and real clicks decide the rank." },
  { path: "/rules", title: "Rules", description: "Surviver.lol rules for entries, what counts as a click, ranking, Rally referrals, refunds, and season survivors." },
  { path: "/privacy", title: "Privacy Policy", description: "Learn how Surviver.lol handles campaign information, payments, analytics, essential cookies, and requests concerning personal information." },
  { path: "/terms", title: "Terms of Service", description: "Review Surviver.lol terms for product submissions, promotional placements, moderation, entry fees, rankings, and refunds." },
  { path: "/sitemap", title: "Site map", description: "Find every public Surviver.lol page, including the discovery board, leaderboard, season archives, competition rules, and entry information." },
] as const;

export function pageMetadata(path: string, title?: string, description?: string): Metadata {
  const page = publicPages.find((page) => page.path === path);
  const resolvedTitle = title ?? page?.title;
  const resolvedDescription = description ?? page?.description;
  return {
    title: resolvedTitle,
    description: resolvedDescription,
    alternates: { canonical: `${SITE_URL}${path === "/" ? "" : path}` },
    openGraph: {
      title: resolvedTitle, description: resolvedDescription, url: `${SITE_URL}${path}`,
      siteName: "Surviver.lol", type: "website",
      images: [SOCIAL_CARD],
    },
    twitter: { card: "summary_large_image", title: resolvedTitle, description: resolvedDescription, images: [SOCIAL_CARD] },
  };
}
